'use client';

import { useMemo, useState } from 'react';
import { Check, Copy, Crosshair, LayoutDashboard, Library, Network, PenLine, Sparkles } from 'lucide-react';

type Target = { target_key: string; route_pattern: string; selector: string; label: string; element_kind: string; description: string; source: string };

export function GuidancePlayground({ targets }: { targets: Target[] }) {
  const routes = useMemo(() => [...new Set(targets.map((target) => target.route_pattern))], [targets]);
  const [route, setRoute] = useState(routes[0] ?? '/write/*');
  const [selected, setSelected] = useState<Target | null>(null);
  const [copied, setCopied] = useState('');
  const visible = targets.filter((target) => target.route_pattern === route || route === '*');
  async function copy(value: string, key: string) { await navigator.clipboard.writeText(value); setCopied(key); window.setTimeout(() => setCopied(''), 1200); }
  return <div className="grid gap-5 xl:grid-cols-[18rem_minmax(0,1fr)_22rem]">
    <aside className="rounded-card border border-line bg-surface p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-accent">Rotas catalogadas</p><button type="button" onClick={() => setRoute('*')} className="mt-3 w-full rounded-xl px-3 py-2 text-left text-xs hover:bg-surface-muted">Todas as rotas</button>{routes.map((item) => <button key={item} type="button" onClick={() => setRoute(item)} className={`mt-1 w-full rounded-xl px-3 py-2 text-left text-xs ${route === item ? 'bg-accent-subtle font-semibold text-accent' : 'hover:bg-surface-muted'}`}>{item}</button>)}</aside>
    <section className="overflow-hidden rounded-card border border-line bg-canvas shadow-soft"><div className="flex items-center justify-between border-b border-line bg-surface px-4 py-3"><div><p className="text-xs font-semibold text-ink">Site liberado para simulação</p><p className="text-[10px] text-muted">Dados de exemplo; nenhuma alteração chega a usuários reais.</p></div><span className="rounded-full bg-success-subtle px-3 py-1 text-[10px] font-semibold text-success">Modo mock</span></div><div className="min-h-[36rem] p-5"><div className="mx-auto flex w-fit items-center gap-1 rounded-full border border-line bg-surface p-1 shadow-soft"><span className="grid size-9 place-items-center rounded-full bg-accent text-on-accent"><Sparkles className="size-4" /></span><span className="rounded-full px-3 py-2 text-xs"><LayoutDashboard className="mr-1.5 inline size-3.5" />Início</span><span className="rounded-full px-3 py-2 text-xs"><Library className="mr-1.5 inline size-3.5" />Biblioteca</span><span className="rounded-full bg-accent-subtle px-3 py-2 text-xs text-accent"><PenLine className="mr-1.5 inline size-3.5" />Escrever</span><span className="rounded-full px-3 py-2 text-xs"><Network className="mr-1.5 inline size-3.5" />Relações</span></div><div className="mx-auto mt-8 max-w-3xl rounded-[1.75rem] border border-line bg-editor p-7"><p className="text-[10px] font-bold uppercase tracking-wider text-accent">{route}</p><h2 className="mt-2 font-serif text-3xl font-semibold">Uma obra de demonstração</h2><p className="mt-2 text-sm text-muted">Todos os recursos aparecem disponíveis para desenhar guias sem alterar permissões reais.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{visible.map((target) => <button key={target.target_key} type="button" onClick={() => setSelected(target)} className={`rounded-2xl border p-4 text-left transition ${selected?.target_key === target.target_key ? 'border-accent bg-accent-subtle' : 'border-line bg-surface hover:border-accent'}`}><Crosshair className="size-4 text-accent" /><strong className="mt-3 block text-sm">{target.label}</strong><span className="mt-1 block text-xs leading-5 text-muted">{target.description}</span><code className="mt-3 block truncate text-[10px] text-accent">{target.selector}</code></button>)}</div></div></div></section>
    <aside className="rounded-card border border-line bg-surface p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-accent">Inspector MCP</p>{selected ? <div className="mt-4 space-y-4"><div><h3 className="font-serif text-xl font-semibold">{selected.label}</h3><p className="mt-2 text-xs leading-5 text-muted">{selected.description}</p></div><dl className="space-y-3 text-xs"><div><dt className="text-muted">Chave</dt><dd className="mt-1 font-mono">{selected.target_key}</dd></div><div><dt className="text-muted">Origem</dt><dd className="mt-1">{selected.source}</dd></div><div><dt className="text-muted">Seletor real</dt><dd className="mt-1 break-all font-mono text-accent">{selected.selector}</dd></div></dl><button type="button" onClick={() => void copy(selected.selector, selected.target_key)} className="inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-xl bg-accent px-4 text-xs font-semibold text-on-accent">{copied === selected.target_key ? <Check className="size-4" /> : <Copy className="size-4" />}Copiar seletor</button><button type="button" onClick={() => void copy(JSON.stringify(selected, null, 2), `${selected.target_key}:manifest`)} className="inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-xl border border-line px-4 text-xs font-semibold"><Copy className="size-4" />Copiar manifesto MCP</button></div> : <p className="mt-4 text-xs leading-6 text-muted">Selecione um elemento no mock para obter o seletor usado pelo produto e o manifesto consumível por automações MCP.</p>}</aside>
  </div>;
}
