'use client';

import { Bell, Bot, Brush, Check, Compass, LockKeyhole, MessageSquare, PenLine, RotateCcw, Save, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { useFormStatus } from 'react-dom';

import { updateAccountPreferences, resetAccountPreferences } from '@/features/account/actions/update-preferences';
import { defaultAccountPreferences, type AccountPreferences } from '@/features/account/preferences';
import { applyAccessibilityPreferences, saveAccessibilityPreferences } from '@/features/accessibility/preferences';
import { cn } from '@/lib/cn';

type Section = 'writing' | 'appearance' | 'notifications' | 'communications' | 'privacy' | 'ai' | 'guidance';
const sections = [
  { id: 'writing' as const, label: 'Escrita', icon: PenLine, description: 'Editor e ritmo' },
  { id: 'appearance' as const, label: 'Aparência', icon: Brush, description: 'Leitura e acesso' },
  { id: 'notifications' as const, label: 'Notificações', icon: Bell, description: 'Alertas importantes' },
  { id: 'communications' as const, label: 'Comunicações', icon: MessageSquare, description: 'Conteúdo editorial' },
  { id: 'privacy' as const, label: 'Privacidade', icon: ShieldCheck, description: 'Dados e descoberta' },
  { id: 'ai' as const, label: 'Copilot IA', icon: Bot, description: 'Contexto permitido' },
  { id: 'guidance' as const, label: 'Guias do produto', icon: Compass, description: 'Tours e dicas' },
];

function SubmitButton() {
  const { pending } = useFormStatus();
  return <button type="submit" disabled={pending} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-accent px-5 text-sm font-semibold text-on-accent shadow-soft hover:bg-accent-hover disabled:opacity-60"><Save className="size-4" />{pending ? 'Salvando…' : 'Salvar preferências'}</button>;
}

function Switch({ name, checked, onChange, title, description, required }: { name: string; checked: boolean; onChange: (checked: boolean) => void; title: string; description: string; required?: boolean }) {
  return <label className="flex cursor-pointer items-start gap-4 rounded-2xl border border-line bg-editor p-4 transition-colors hover:border-line-strong"><span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-sm font-semibold text-ink">{title}{required && <LockKeyhole className="size-3.5 text-muted" />}</span><span className="mt-1 block text-xs leading-5 text-muted">{description}</span></span><input type="checkbox" name={name} checked={checked} onChange={(event) => onChange(event.target.checked)} disabled={required} className="peer sr-only" /><span className={cn('relative mt-0.5 h-6 w-11 shrink-0 rounded-full border transition-colors after:absolute after:left-0.5 after:top-0.5 after:size-5 after:rounded-full after:bg-white after:shadow-sm after:transition-transform', checked ? 'border-accent bg-accent after:translate-x-5' : 'border-line-strong bg-surface-muted')} aria-hidden="true" /></label>;
}

function SectionHeader({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <div className="mb-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-accent">{eyebrow}</p><h2 className="mt-2 font-serif text-2xl font-semibold text-ink sm:text-3xl">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">{description}</p></div>;
}

export function PreferencesForm({ initial, saved, reset }: { initial: AccountPreferences; saved?: boolean; reset?: boolean }) {
  const [active, setActive] = useState<Section>('writing');
  const [values, setValues] = useState(initial);
  const appearance = values.appearance;

  function applyAppearance(next: AccountPreferences['appearance']) {
    setValues((current) => ({ ...current, appearance: next }));
    const accessible = { theme: next.theme, fontSize: next.fontSize, lineHeight: next.lineHeight, textWidth: next.textWidth, reduceMotion: next.reduceMotion, highContrast: next.highContrast };
    applyAccessibilityPreferences(accessible); saveAccessibilityPreferences(accessible);
  }

  return <div>
    {(saved || reset) && <div className="mb-5 flex items-center gap-3 rounded-2xl border border-success/25 bg-success-subtle px-4 py-3 text-sm text-ink" role="status"><span className="flex size-7 items-center justify-center rounded-full bg-success text-white"><Check className="size-4" /></span>{reset ? 'Preferências restauradas para o padrão editorial.' : 'Preferências atualizadas em todos os seus dispositivos.'}</div>}
    <form action={updateAccountPreferences} onSubmit={() => { const next = values.appearance; applyAccessibilityPreferences(next); saveAccessibilityPreferences(next); }}>
      <div className="grid items-start gap-5 xl:grid-cols-[15rem_minmax(0,1fr)]">
        <nav className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:sticky xl:top-24 xl:grid-cols-1" aria-label="Categorias de preferências">{sections.map(({ id, label, icon: Icon, description }) => <button key={id} type="button" onClick={() => setActive(id)} aria-current={active === id ? 'page' : undefined} className={cn('flex min-h-14 items-center gap-3 rounded-xl border px-3 text-left transition-colors', active === id ? 'border-accent bg-accent-subtle text-accent' : 'border-transparent text-muted hover:border-line hover:bg-surface')}><Icon className="size-4 shrink-0" /><span className="min-w-0"><span className="block truncate text-sm font-semibold">{label}</span><span className="hidden truncate text-[10px] opacity-80 sm:block">{description}</span></span></button>)}</nav>
        <section data-tour="account-preferences" className="min-w-0 rounded-[1.75rem] border border-line bg-surface p-5 shadow-soft sm:p-8">
          {active === 'writing' && <><SectionHeader eyebrow="Seu processo" title="Como o editor trabalha com você" description="Defina padrões que reduzam decisões repetitivas. Cada obra ainda pode substituir essas escolhas." /><div className="grid gap-4 sm:grid-cols-2"><label className="rounded-2xl border border-line bg-editor p-4 text-sm font-semibold text-ink">Meta diária de palavras<input type="number" name="dailyGoal" min="0" max="100000" value={values.writing.dailyGoal} onChange={(event) => setValues({ ...values, writing: { ...values.writing, dailyGoal: Number(event.target.value) } })} className="mt-3 min-h-11 w-full rounded-xl border border-line bg-surface px-3 text-sm" /><span className="mt-2 block text-xs font-normal text-muted">Use zero para escrever sem meta.</span></label><label className="rounded-2xl border border-line bg-editor p-4 text-sm font-semibold text-ink">Visualização inicial<select name="pagePreset" value={values.writing.pagePreset} onChange={(event) => setValues({ ...values, writing: { ...values.writing, pagePreset: event.target.value as AccountPreferences['writing']['pagePreset'] } })} className="mt-3 min-h-11 w-full rounded-xl border border-line bg-surface px-3 text-sm"><option value="continuous">Canvas contínuo</option><option value="book">Livro 152 × 229 mm</option><option value="a4">Página A4</option></select><span className="mt-2 block text-xs font-normal text-muted">A obra pode usar outro formato.</span></label></div><div className="mt-4 grid gap-3"><Switch name="autosave" checked={values.writing.autosave} onChange={(autosave) => setValues({ ...values, writing: { ...values.writing, autosave } })} title="Salvamento automático" description="Salva alterações enquanto você escreve e sincroniza quando houver conexão." /><Switch name="spellcheck" checked={values.writing.spellcheck} onChange={(spellcheck) => setValues({ ...values, writing: { ...values.writing, spellcheck } })} title="Correção ortográfica do navegador" description="Sublinhe possíveis erros sem enviar o manuscrito para análise externa." /><Switch name="openLastWork" checked={values.writing.openLastWork} onChange={(openLastWork) => setValues({ ...values, writing: { ...values.writing, openLastWork } })} title="Retomar a última obra" description="Abra o documento mais recente ao entrar no ambiente de escrita." /><Switch name="focusMode" checked={values.writing.focusMode} onChange={(focusMode) => setValues({ ...values, writing: { ...values.writing, focusMode } })} title="Começar em modo foco" description="Recolha painéis auxiliares ao abrir o editor." /></div></>}
          {active === 'appearance' && <><SectionHeader eyebrow="Conforto visual" title="Aparência e acessibilidade" description="As mudanças são aplicadas imediatamente e sincronizadas quando você salva." /><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold text-ink">Tema<select name="theme" value={appearance.theme} onChange={(event) => applyAppearance({ ...appearance, theme: event.target.value as typeof appearance.theme })} className="mt-2 min-h-11 w-full rounded-xl border border-line bg-editor px-3 text-sm"><option value="system">Acompanhar sistema</option><option value="light">Claro</option><option value="dark">Escuro</option></select></label><label className="text-xs font-semibold text-ink">Tamanho da fonte · {appearance.fontSize}px<input name="fontSize" type="range" min="16" max="24" value={appearance.fontSize} onChange={(event) => applyAppearance({ ...appearance, fontSize: Number(event.target.value) })} className="mt-4 w-full accent-accent" /></label><label className="text-xs font-semibold text-ink">Entrelinha<select name="lineHeight" value={appearance.lineHeight} onChange={(event) => applyAppearance({ ...appearance, lineHeight: Number(event.target.value) as typeof appearance.lineHeight })} className="mt-2 min-h-11 w-full rounded-xl border border-line bg-editor px-3 text-sm"><option value="1.5">Compacta</option><option value="1.65">Confortável</option><option value="1.8">Ampla</option></select></label><label className="text-xs font-semibold text-ink">Largura do texto<select name="textWidth" value={appearance.textWidth} onChange={(event) => applyAppearance({ ...appearance, textWidth: Number(event.target.value) as typeof appearance.textWidth })} className="mt-2 min-h-11 w-full rounded-xl border border-line bg-editor px-3 text-sm"><option value="60">Estreita</option><option value="68">Padrão</option><option value="75">Larga</option></select></label></div><div className="mt-5 grid gap-3"><Switch name="reduceMotion" checked={appearance.reduceMotion} onChange={(reduceMotion) => applyAppearance({ ...appearance, reduceMotion })} title="Reduzir animações" description="Simplifica transições, movimentos e efeitos pulsantes." /><Switch name="highContrast" checked={appearance.highContrast} onChange={(highContrast) => applyAppearance({ ...appearance, highContrast })} title="Contraste reforçado" description="Aumenta a separação entre texto, superfícies e bordas." /></div><div className="mt-5 rounded-2xl border border-line bg-editor p-6"><p className="font-serif text-xl text-ink">Uma página confortável deixa a história ocupar o primeiro plano.</p><p className="mt-3 max-w-[68ch] text-sm leading-relaxed text-muted">Esta prévia responde ao tema, tamanho e espaçamento escolhidos. O conteúdo do manuscrito continua privado.</p></div></>}
          {active === 'notifications' && <><SectionHeader eyebrow="Sua atenção" title="Notificações com propósito" description="Escolha quais eventos merecem interromper você. Alertas de segurança permanecem ativos." /><div className="grid gap-3"><Switch name="inApp" checked={values.notifications.inApp} onChange={(inApp) => setValues({ ...values, notifications: { ...values.notifications, inApp } })} title="Central de notificações" description="Mostre menções, convites e atualizações dentro do Autor Copilot." /><Switch name="emailMentions" checked={values.notifications.emailMentions} onChange={(emailMentions) => setValues({ ...values, notifications: { ...values.notifications, emailMentions } })} title="Menções por e-mail" description="Avise quando um colaborador mencionar você." /><Switch name="emailReminders" checked={values.notifications.emailReminders} onChange={(emailReminders) => setValues({ ...values, notifications: { ...values.notifications, emailReminders } })} title="Lembretes editoriais" description="Receba lembretes de prazos e revisões planejadas." /><Switch name="goalReminders" checked={values.notifications.goalReminders} onChange={(goalReminders) => setValues({ ...values, notifications: { ...values.notifications, goalReminders } })} title="Lembretes de meta" description="Lembretes suaves baseados na meta que você definiu." /><Switch name="collaboration" checked={values.notifications.collaboration} onChange={(collaboration) => setValues({ ...values, notifications: { ...values.notifications, collaboration } })} title="Atividade de colaboração" description="Convites, comentários e mudanças de papel nos seus espaços." /><Switch name="security" checked title="Segurança da conta" description="Novo login, troca de e-mail e eventos críticos." required onChange={() => undefined} /><input type="hidden" name="security" value="on" /></div></>}
          {active === 'communications' && <><SectionHeader eyebrow="Conteúdo escolhido" title="Comunicações do Autor Copilot" description="Controle novidades e conteúdo editorial separadamente das notificações da sua obra." /><div className="grid gap-3"><Switch name="productUpdates" checked={values.communications.productUpdates} onChange={(productUpdates) => setValues({ ...values, communications: { ...values.communications, productUpdates } })} title="Novidades do produto" description="Lançamentos relevantes e mudanças de recursos." /><Switch name="changelog" checked={values.communications.changelog} onChange={(changelog) => setValues({ ...values, communications: { ...values.communications, changelog } })} title="Resumo do changelog" description="Uma seleção periódica das melhorias publicadas." /><Switch name="editorialDigest" checked={values.communications.editorialDigest} onChange={(editorialDigest) => setValues({ ...values, communications: { ...values.communications, editorialDigest } })} title="Caderno editorial" description="Guias, entrevistas e práticas de escrita." /><Switch name="researchInvites" checked={values.communications.researchInvites} onChange={(researchInvites) => setValues({ ...values, communications: { ...values.communications, researchInvites } })} title="Convites para pesquisa" description="Oportunidades voluntárias de testar conceitos e conversar com o time." /></div></>}
          {active === 'privacy' && <><SectionHeader eyebrow="Privacidade previsível" title="Seus dados, com limites claros" description="Metadados de uso nunca incluem nomes, enredo ou texto do manuscrito. Análise de prosa exige consentimento separado." /><div className="mb-5 rounded-2xl border border-accent/20 bg-accent-subtle p-5"><ShieldCheck className="size-5 text-accent" /><p className="mt-3 text-sm font-semibold text-ink">O vetor comportamental bruto nunca aparece aqui.</p><p className="mt-1 text-xs leading-5 text-muted">Você vê apenas seu arquétipo explicável. O vetor interno usa sinais estruturais de uso e não determina preço individual automaticamente.</p></div><div className="grid gap-3"><Switch name="usageMetadata" checked={values.privacy.usageMetadata} onChange={(usageMetadata) => setValues({ ...values, privacy: { ...values.privacy, usageMetadata } })} title="Metadados estruturais de uso" description="Ajude a personalizar recursos usando frequência, sessões e adoção de ferramentas, sem ler o texto." /><Switch name="personalizedRecommendations" checked={values.privacy.personalizedRecommendations} onChange={(personalizedRecommendations) => setValues({ ...values, privacy: { ...values.privacy, personalizedRecommendations } })} title="Recomendações personalizadas" description="Sugira templates e módulos a partir de padrões agregados e do seu próprio histórico." /><Switch name="publicProfile" checked={values.privacy.publicProfile} onChange={(publicProfile) => setValues({ ...values, privacy: { ...values.privacy, publicProfile } })} title="Perfil público de autor" description="Permita que seu nome literário e biografia apareçam em áreas de descoberta." /><Switch name="compatibilityDiscovery" checked={values.privacy.compatibilityDiscovery} onChange={(compatibilityDiscovery) => setValues({ ...values, privacy: { ...values.privacy, compatibilityDiscovery } })} title="Descoberta por compatibilidade" description="Participe de sugestões mútuas de autores, editores e consultores." /><Switch name="proseAnalysisConsent" checked={values.privacy.proseAnalysisConsent} onChange={(proseAnalysisConsent) => setValues({ ...values, privacy: { ...values.privacy, proseAnalysisConsent } })} title="Análise de estilo da prosa" description="Consentimento separado para analisar características do texto. Desligado por padrão e revogável." /></div></>}
          {active === 'ai' && <><SectionHeader eyebrow="Contexto sob controle" title="Autor Copilot IA" description="Defina as fontes que a assistência pode consultar. Antes de qualquer envio externo, o produto deve mostrar o conteúdo e o destino." /><div className="grid gap-3"><Switch name="aiEnabled" checked={values.ai.enabled} onChange={(enabled) => setValues({ ...values, ai: { ...values.ai, enabled } })} title="Ativar assistência de IA" description="Disponibilize ações assistidas quando você solicitar." /><Switch name="useCurrentChapter" checked={values.ai.useCurrentChapter} onChange={(useCurrentChapter) => setValues({ ...values, ai: { ...values.ai, useCurrentChapter } })} title="Capítulo aberto" description="Permita usar o trecho atual como contexto de uma solicitação explícita." /><Switch name="useEncyclopedia" checked={values.ai.useEncyclopedia} onChange={(useEncyclopedia) => setValues({ ...values, ai: { ...values.ai, useEncyclopedia } })} title="Enciclopédia e referências @" description="Inclua fichas vinculadas para manter nomes e regras coerentes." /><Switch name="useOtherWorks" checked={values.ai.useOtherWorks} onChange={(useOtherWorks) => setValues({ ...values, ai: { ...values.ai, useOtherWorks } })} title="Outras obras do projeto" description="Autorize contexto entre livros conectados ao mesmo projeto." /><Switch name="rememberInstructions" checked={values.ai.rememberInstructions} onChange={(rememberInstructions) => setValues({ ...values, ai: { ...values.ai, rememberInstructions } })} title="Lembrar instruções editoriais" description="Guarde preferências de tom e formato, sem memorizar automaticamente o manuscrito." /></div></>}
          {active === 'guidance' && <><SectionHeader eyebrow="Aprender no contexto" title="Tours, coach marks e hotspots" description="Controle as orientações criadas para novos recursos. Você pode dispensar cada experiência individualmente." /><div className="grid gap-3"><Switch name="guidanceEnabled" checked={values.guidance.enabled} onChange={(enabled) => setValues({ ...values, guidance: { ...values.guidance, enabled } })} title="Guias do produto" description="Permita jornadas curtas quando uma área ou função for nova para você." /><Switch name="hotspots" checked={values.guidance.hotspots} onChange={(hotspots) => setValues({ ...values, guidance: { ...values.guidance, hotspots } })} title="Pontos de descoberta" description="Mostre pontos pulsantes discretos em recursos ainda não explorados." /><Switch name="announcements" checked={values.guidance.announcements} onChange={(announcements) => setValues({ ...values, guidance: { ...values.guidance, announcements } })} title="Reapresentar grandes novidades" description="Aceite novos tours quando uma função mudar de forma relevante." /></div><p className="mt-5 rounded-xl border border-line bg-editor p-4 text-xs leading-5 text-muted">O Admin pode relançar uma experiência com uma nova versão. Suas escolhas de desativação global continuam sendo respeitadas.</p></>}
        </section>
      </div>
      <div className="sticky bottom-4 z-20 mt-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-line bg-surface/95 p-3 shadow-floating backdrop-blur-xl"><p className="hidden text-xs text-muted sm:block">As alterações visuais já aparecem nesta tela.</p><SubmitButton /></div>
    </form>
    <form action={resetAccountPreferences} onSubmit={() => { applyAccessibilityPreferences(defaultAccountPreferences.appearance); saveAccessibilityPreferences(defaultAccountPreferences.appearance); }} className="mt-3 text-right"><button type="submit" className="inline-flex min-h-10 items-center gap-2 rounded-full px-4 text-xs font-semibold text-muted hover:bg-surface-muted hover:text-ink"><RotateCcw className="size-3.5" />Restaurar todos os padrões</button></form>
  </div>;
}
