import { ArrowRight, BookOpen, CalendarDays, Check, CircleDot, FileText, Flag, Goal, Layers3, MoreHorizontal, NotebookPen, PenLine, StickyNote, Trash2, TrendingUp } from 'lucide-react';
import Link from 'next/link';

import { Badge, buttonVariants, DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui';
import { deleteWritingGoal, toggleWritingGoal } from '@/features/overview/actions';
import { NewGoalDialog } from '@/features/overview/components/new-goal-dialog';
import type { OverviewDocument, OverviewGoal, OverviewView, OverviewWork } from '@/features/overview/types';
import { goalTypeLabels } from '@/features/overview/types';
import { kindLabels, statusLabels } from '@/features/writing/types';
import { cn } from '@/lib/cn';

const viewMeta: Record<OverviewView, { eyebrow: string; title: string; description: string }> = {
  dashboard: { eyebrow: 'Visão geral', title: 'Painel da obra', description: 'Acompanhe o tamanho, a estrutura e o ritmo atual do seu manuscrito.' },
  activity: { eyebrow: 'Rastro de escrita', title: 'Atividade', description: 'Veja quais partes da obra receberam atenção mais recentemente.' },
  goals: { eyebrow: 'Direção editorial', title: 'Metas de escrita', description: 'Defina marcos e acompanhe o avanço real do manuscrito.' },
};

function number(value: number) { return new Intl.NumberFormat('pt-BR').format(value); }
function date(value: string) { return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)); }
function relativeDate(value: string) {
  const days = Math.floor((Date.now() - Date.parse(value)) / 86400000);
  if (days <= 0) return 'Hoje';
  if (days === 1) return 'Ontem';
  if (days < 7) return `Há ${days} dias`;
  return date(value);
}

function WorkSelector({ works, selectedWork, view }: { works: OverviewWork[]; selectedWork: OverviewWork; view: OverviewView }) {
  return <form action={`/overview/${view}`} className="flex flex-col gap-2 sm:flex-row"><select name="work" defaultValue={selectedWork.id} aria-label="Selecionar obra" className="min-h-11 min-w-60 rounded-full border border-line bg-surface px-4 text-sm shadow-soft">{works.map((work) => <option key={work.id} value={work.id}>{work.title}</option>)}</select><button type="submit" className={cn(buttonVariants({ variant: 'secondary' }), 'rounded-full')}>Abrir painel</button></form>;
}

function Metric({ icon: Icon, value, label }: { icon: typeof BookOpen; value: string; label: string }) {
  return <div className="border-b border-line py-5 sm:border-b-0 sm:border-r sm:px-5 sm:first:pl-0 sm:last:border-r-0"><Icon className="size-4 text-accent" /><p className="mt-3 text-2xl font-semibold text-ink">{value}</p><p className="mt-0.5 text-xs text-muted">{label}</p></div>;
}

function RecentDocuments({ documents, workId }: { documents: OverviewDocument[]; workId: string }) {
  return <div className="divide-y divide-line">{documents.slice(0, 6).map((document) => <Link key={document.id} href={`/write/editor?work=${workId}&document=${document.id}`} className="group flex items-center gap-4 py-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-accent-subtle text-accent"><FileText className="size-4" /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium text-ink">{document.title}</span><span className="mt-1 block text-xs text-muted">{kindLabels[document.kind]} · {number(document.wordCount)} palavras · {statusLabels[document.status]}</span></span><span className="hidden text-xs text-muted sm:block">{relativeDate(document.updatedAt)}</span><ArrowRight className="size-3.5 text-muted transition-transform group-hover:translate-x-1" /></Link>)}</div>;
}

function GoalCard({ goal, workId }: { goal: OverviewGoal; workId: string }) {
  const complete = Boolean(goal.completedAt);
  return <article className={cn('rounded-card border bg-surface p-5 shadow-soft', complete ? 'border-success/40' : 'border-line')}>
    <div className="flex items-start justify-between gap-3"><span className={cn('flex size-10 items-center justify-center rounded-full', complete ? 'bg-success-subtle text-success' : 'bg-accent-subtle text-accent')}>{complete ? <Check className="size-4" /> : <Flag className="size-4" />}</span><DropdownMenu><DropdownMenuTrigger className="flex size-9 items-center justify-center rounded-full text-muted hover:bg-surface-muted" aria-label="Ações da meta"><MoreHorizontal className="size-4" /></DropdownMenuTrigger><DropdownMenuContent align="end"><form action={toggleWritingGoal}><input type="hidden" name="workId" value={workId} /><input type="hidden" name="goalId" value={goal.id} /><input type="hidden" name="completed" value={String(!complete)} /><DropdownMenuItem asChild><button type="submit" className="w-full"><Check className="size-4" />{complete ? 'Reabrir meta' : 'Marcar como concluída'}</button></DropdownMenuItem></form><DropdownMenuSeparator /><form action={deleteWritingGoal}><input type="hidden" name="workId" value={workId} /><input type="hidden" name="goalId" value={goal.id} /><DropdownMenuItem asChild><button type="submit" className="w-full text-danger"><Trash2 className="size-4" />Apagar meta</button></DropdownMenuItem></form></DropdownMenuContent></DropdownMenu></div>
    <p className="mt-4 text-[10px] font-semibold uppercase tracking-[0.16em] text-accent">{goalTypeLabels[goal.type]}</p><h3 className="mt-1 font-serif text-xl font-semibold text-ink">{goal.title}</h3>
    <div className="mt-5 flex items-end justify-between"><div><p className="text-sm font-semibold text-ink">{goal.type === 'deadline' ? complete ? 'Concluída' : 'Em andamento' : `${number(goal.current)} de ${number(goal.target)}`}</p>{goal.dueDate && <p className="mt-1 text-xs text-muted"><CalendarDays className="mr-1 inline size-3" />Até {date(goal.dueDate)}</p>}</div><span className="text-lg font-semibold text-accent">{goal.progress}%</span></div>
    <div className="mt-3 h-1.5 overflow-hidden rounded-full bg-line"><div className={cn('h-full rounded-full', complete ? 'bg-success' : 'bg-accent')} style={{ width: `${goal.progress}%` }} /></div>
  </article>;
}

export function OverviewPage({ view, works, selectedWork, documents, goals, metrics }: { view: OverviewView; works: OverviewWork[]; selectedWork: OverviewWork | null; documents: OverviewDocument[]; goals: OverviewGoal[]; metrics: { words: number; chapters: number; scenes: number; notes: number; completed: number; progress: number } }) {
  if (!selectedWork) return <div className="mx-auto max-w-4xl py-16"><BookOpen className="size-8 text-accent" /><h1 className="mt-5 font-serif text-4xl font-semibold">Nenhuma obra ativa</h1><p className="mt-3 text-muted">Crie ou restaure uma obra para acompanhar sua visão geral.</p><Link href="/library/all" className={cn(buttonVariants(), 'mt-6')}>Abrir Biblioteca</Link></div>;
  const meta = viewMeta[view];
  const tabs = [['dashboard', 'Painel da obra'], ['activity', 'Atividade'], ['goals', 'Metas']] as const;
  return <div className="mx-auto w-full max-w-7xl py-4 sm:py-7">
    <section className="relative isolate overflow-hidden rounded-card border border-line bg-editor px-6 py-8 shadow-soft sm:px-10 sm:py-10"><div className="absolute inset-0 -z-20 bg-[url('/images/kit_marca/03_backgrounds/papel-claro.svg')] bg-cover opacity-45 dark:opacity-[0.06]" /><div className="absolute -right-20 -top-32 -z-10 size-80 rounded-full bg-accent-subtle blur-3xl" /><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-accent">{meta.eyebrow}</p><h1 className="mt-3 font-serif text-4xl font-semibold text-ink sm:text-5xl">{meta.title}</h1><p className="mt-4 text-base leading-relaxed text-muted">{meta.description}</p><div className="mt-5 flex flex-wrap items-center gap-2"><Badge>{selectedWork.genre}</Badge><span className="text-xs text-muted">{selectedWork.title}</span></div></div><WorkSelector works={works} selectedWork={selectedWork} view={view} /></div></section>
    <nav className="workspace-scrollbar mt-7 flex gap-1 overflow-x-auto border-b border-line" aria-label="Visão geral da obra">{tabs.map(([key, label]) => <Link key={key} href={`/overview/${key}?work=${selectedWork.id}`} className={cn('whitespace-nowrap border-b-2 px-4 py-3 text-sm font-medium', view === key ? 'border-accent text-accent' : 'border-transparent text-muted hover:text-ink')}>{label}</Link>)}</nav>

    {view === 'dashboard' && <><section className="grid sm:grid-cols-5" aria-label="Métricas da obra"><Metric icon={PenLine} value={number(metrics.words)} label="palavras" /><Metric icon={Layers3} value={number(metrics.chapters)} label="capítulos" /><Metric icon={NotebookPen} value={number(metrics.scenes)} label="cenas" /><Metric icon={StickyNote} value={number(metrics.notes)} label="notas" /><Metric icon={Check} value={number(metrics.completed)} label="documentos finais" /></section><div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1.35fr)_minmax(18rem,.65fr)]"><section><div className="flex items-end justify-between border-b border-line pb-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">Últimos movimentos</p><h2 className="mt-1 font-serif text-2xl font-semibold">Documentos recentes</h2></div><Link href={`/overview/activity?work=${selectedWork.id}`} className="text-xs font-medium text-accent hover:underline">Ver atividade</Link></div><RecentDocuments documents={documents} workId={selectedWork.id} /></section><aside className="rounded-card border border-line bg-surface p-6 shadow-soft"><div className="mx-auto flex size-40 items-center justify-center rounded-full" style={{ background: `conic-gradient(var(--color-accent) ${metrics.progress}%, var(--color-border) 0)` }}><div className="flex size-32 flex-col items-center justify-center rounded-full bg-surface"><span className="text-3xl font-semibold text-ink">{metrics.progress}%</span><span className="text-xs text-muted">da meta</span></div></div><h2 className="mt-6 text-center font-serif text-xl font-semibold">Progresso da obra</h2><p className="mt-2 text-center text-sm text-muted">{number(metrics.words)} de {number(selectedWork.wordGoal)} palavras</p><Link href={`/overview/goals?work=${selectedWork.id}`} className={cn(buttonVariants({ variant: 'secondary' }), 'mt-5 w-full')}>Gerenciar metas</Link></aside></div></>}

    {view === 'activity' && <section className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_18rem]"><div><div className="border-b border-line pb-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">Linha do tempo</p><h2 className="mt-1 font-serif text-2xl font-semibold">Movimentos recentes</h2></div><ol className="mt-2">{documents.map((document, index) => <li key={document.id} className="relative grid grid-cols-[2rem_1fr] gap-4 pb-1"><div className="flex flex-col items-center"><span className="mt-5 flex size-8 items-center justify-center rounded-full border border-line bg-surface text-accent"><CircleDot className="size-3.5" /></span>{index < documents.length - 1 && <span className="w-px flex-1 bg-line" />}</div><Link href={`/write/editor?work=${selectedWork.id}&document=${document.id}`} className="group flex items-center justify-between gap-4 border-b border-line py-5"><div><p className="text-sm font-medium text-ink">{document.title}</p><p className="mt-1 text-xs text-muted">{kindLabels[document.kind]} atualizado · {number(document.wordCount)} palavras</p></div><span className="shrink-0 text-xs text-muted">{relativeDate(document.updatedAt)}</span></Link></li>)}</ol></div><aside className="border-l-2 border-accent px-5 py-2"><TrendingUp className="size-5 text-accent" /><h2 className="mt-4 font-serif text-xl font-semibold">Pulso da obra</h2><p className="mt-2 text-sm leading-relaxed text-muted">{documents.length} documentos compõem este manuscrito. A atividade reflete a última alteração registrada em cada parte.</p><Link href={`/write/editor?work=${selectedWork.id}`} className="mt-5 inline-flex items-center gap-2 text-sm font-medium text-accent">Continuar escrevendo<ArrowRight className="size-4" /></Link></aside></section>}

    {view === 'goals' && <section className="mt-8"><div className="flex flex-col gap-4 border-b border-line pb-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">Marcos editoriais</p><h2 className="mt-1 font-serif text-2xl font-semibold">Metas da obra</h2></div><NewGoalDialog workId={selectedWork.id} /></div>{goals.length ? <div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{goals.map((goal) => <GoalCard key={goal.id} goal={goal} workId={selectedWork.id} />)}</div> : <div className="mt-6 flex min-h-64 items-center rounded-card border border-dashed border-line-strong p-8"><div><Goal className="size-7 text-accent" /><h3 className="mt-4 font-serif text-2xl font-semibold">Defina o próximo marco</h3><p className="mt-2 max-w-md text-sm text-muted">Crie uma meta de palavras, capítulos ou prazo para orientar o avanço da obra.</p><div className="mt-5"><NewGoalDialog workId={selectedWork.id} /></div></div></div>}</section>}
  </div>;
}
