import { ArrowUpRight, FileText, Megaphone, RefreshCw, Save } from 'lucide-react';
import Link from 'next/link';

import { PendingSubmitButton } from '@/components/ui';
import { syncLegalDocuments, updateLegalDocument } from '@/features/admin/actions/product-controls';
import { requireAdmin } from '@/features/admin/auth';
import { createAdminClient } from '@/lib/supabase/admin';

const inputClass = 'mt-1.5 min-h-10 w-full rounded-control border border-line bg-editor px-3 text-ink';

export default async function AdminLegalPage() {
  const admin = await requireAdmin('legal.read');
  const supabase = createAdminClient();
  const [{ data: documents, error }, { count: omniCount }] = await Promise.all([
    supabase.from('legal_documents').select('*').order('title'),
    supabase.from('communication_items').select('id', { count: 'exact', head: true }).eq('channel', 'legal'),
  ]);
  return <div>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[0.2em] text-accent">Governança jurídica</p><h1 className="mt-2 text-3xl font-semibold">Documentos legais</h1><p className="mt-3 text-sm text-muted">Edite o acervo vigente ou publique uma nova versão pelo fluxo editorial do OmniPublish.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/publish/new?channel=legal" className="inline-flex min-h-11 items-center gap-2 rounded-control bg-accent px-4 text-sm font-semibold text-on-accent"><Megaphone className="size-4" />Nova versão no OmniPublish</Link>{admin.role !== 'director' && <form action={syncLegalDocuments}><PendingSubmitButton pendingLabel="Importando…" className="min-h-11 rounded-control border border-line bg-surface px-4 text-sm font-medium hover:bg-surface-muted"><RefreshCw className="size-4" />Importar código</PendingSubmitButton></form>}</div></div>
    <div className="mt-7 grid gap-3 sm:grid-cols-3"><article className="rounded-2xl border border-line bg-surface p-5"><p className="text-xs text-muted">Documentos vigentes</p><strong className="mt-2 block font-serif text-3xl">{documents?.filter((item) => item.is_published).length ?? 0}</strong></article><article className="rounded-2xl border border-line bg-surface p-5"><p className="text-xs text-muted">Peças jurídicas no OmniPublish</p><strong className="mt-2 block font-serif text-3xl">{omniCount ?? 0}</strong></article><Link href="/legal" target="_blank" className="group rounded-2xl border border-line bg-accent-subtle p-5"><p className="text-xs text-accent">Catálogo público</p><strong className="mt-2 flex items-center gap-2 font-serif text-lg">Abrir /legal <ArrowUpRight className="size-4 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></strong></Link></div>
    {error ? <p className="mt-7 rounded-control border border-amber-400/20 bg-amber-400/10 p-4 text-warning">As tabelas administrativas ainda não existem no Supabase conectado. Execute <code className="rounded bg-surface-muted px-1.5 py-0.5">npx supabase db push</code> após autenticar a CLI. {error.message}</p> : documents?.length ? <div className="mt-7 space-y-4">{documents.map((document) => <form key={document.slug} action={updateLegalDocument} className="rounded-card border border-line bg-surface p-5"><input type="hidden" name="slug" value={document.slug} /><div className="flex items-start gap-3"><FileText className="mt-1 size-5 shrink-0 text-accent" /><div className="min-w-0 flex-1"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs text-muted sm:col-span-2">Título<input name="title" defaultValue={document.title} className={inputClass} /></label><label className="text-xs text-muted">Versão<input name="version" defaultValue={document.version} className={inputClass} /></label><label className="text-xs text-muted">Vigência<input name="effective_at" type="date" defaultValue={document.effective_at} className={inputClass} /></label><label className="text-xs text-muted sm:col-span-2">Descrição<input name="short_description" defaultValue={document.short_description} className={inputClass} /></label><label className="text-xs text-muted">Departamento<input name="department" defaultValue={document.department} className={inputClass} /></label><label className="text-xs text-muted">Recursos relacionados<input name="related_features" defaultValue={document.related_features.join(', ')} className={inputClass} /></label></div><label className="mt-4 block text-xs text-muted">Conteúdo das seções em JSON<textarea name="sections" defaultValue={JSON.stringify(document.sections, null, 2)} rows={10} className="mt-1.5 w-full resize-y rounded-control border border-line bg-editor px-3 py-2 font-mono text-xs leading-relaxed text-ink" /></label></div><div className="flex shrink-0 flex-col items-end gap-3"><label className="flex items-center gap-2 text-xs text-muted"><input name="is_published" type="checkbox" defaultChecked={document.is_published} />Publicado</label><PendingSubmitButton pendingLabel="Salvando…" className="min-h-10 rounded-control bg-accent text-on-accent px-3 text-sm font-medium hover:bg-accent-hover"><Save className="size-4" />Salvar</PendingSubmitButton></div></div></form>)}</div> : <div className="mt-7 rounded-card border border-dashed border-line-strong p-10 text-center text-sm text-muted">Importe os oito documentos atuais para iniciar a gestão.</div>}
  </div>;
}
