import { FileText, RefreshCw, Save } from 'lucide-react';

import { PendingSubmitButton } from '@/components/ui';
import { syncLegalDocuments, updateLegalDocument } from '@/features/admin/actions/product-controls';
import { requireAdmin } from '@/features/admin/auth';
import { createAdminClient } from '@/lib/supabase/admin';

const inputClass = 'mt-1.5 min-h-10 w-full rounded-control border border-white/10 bg-black/25 px-3 text-white';

export default async function AdminLegalPage() {
  const admin = await requireAdmin('legal.read');
  const supabase = createAdminClient();
  const { data: documents, error } = await supabase.from('legal_documents').select('*').order('title');
  return <div>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[0.2em] text-emerald-300">Governança jurídica</p><h1 className="mt-2 text-3xl font-semibold">Documentos legais</h1><p className="mt-3 text-sm text-white/50">Edite conteúdo, versão, vigência e publicação dos termos usados na plataforma.</p></div>{admin.role !== 'director' && <form action={syncLegalDocuments}><PendingSubmitButton pendingLabel="Importando…" className="min-h-11 rounded-control border border-emerald-500 bg-emerald-600 px-4 text-sm font-medium hover:bg-emerald-500"><RefreshCw className="size-4" />Importar documentos do código</PendingSubmitButton></form>}</div>
    {error ? <p className="mt-7 rounded-control border border-amber-400/20 bg-amber-400/10 p-4 text-amber-200">As tabelas administrativas ainda não existem no Supabase conectado. Execute <code className="rounded bg-black/20 px-1.5 py-0.5">npx supabase db push</code> após autenticar a CLI. {error.message}</p> : documents?.length ? <div className="mt-7 space-y-4">{documents.map((document) => <form key={document.slug} action={updateLegalDocument} className="rounded-card border border-white/10 bg-white/[0.035] p-5"><input type="hidden" name="slug" value={document.slug} /><div className="flex items-start gap-3"><FileText className="mt-1 size-5 shrink-0 text-emerald-300" /><div className="min-w-0 flex-1"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs text-white/55 sm:col-span-2">Título<input name="title" defaultValue={document.title} className={inputClass} /></label><label className="text-xs text-white/55">Versão<input name="version" defaultValue={document.version} className={inputClass} /></label><label className="text-xs text-white/55">Vigência<input name="effective_at" type="date" defaultValue={document.effective_at} className={inputClass} /></label><label className="text-xs text-white/55 sm:col-span-2">Descrição<input name="short_description" defaultValue={document.short_description} className={inputClass} /></label><label className="text-xs text-white/55">Departamento<input name="department" defaultValue={document.department} className={inputClass} /></label><label className="text-xs text-white/55">Recursos relacionados<input name="related_features" defaultValue={document.related_features.join(', ')} className={inputClass} /></label></div><label className="mt-4 block text-xs text-white/55">Conteúdo das seções em JSON<textarea name="sections" defaultValue={JSON.stringify(document.sections, null, 2)} rows={10} className="mt-1.5 w-full resize-y rounded-control border border-white/10 bg-black/25 px-3 py-2 font-mono text-xs leading-relaxed text-white" /></label></div><div className="flex shrink-0 flex-col items-end gap-3"><label className="flex items-center gap-2 text-xs text-white/60"><input name="is_published" type="checkbox" defaultChecked={document.is_published} />Publicado</label><PendingSubmitButton pendingLabel="Salvando…" className="min-h-10 rounded-control bg-emerald-600 px-3 text-sm font-medium hover:bg-emerald-500"><Save className="size-4" />Salvar</PendingSubmitButton></div></div></form>)}</div> : <div className="mt-7 rounded-card border border-dashed border-white/15 p-10 text-center text-sm text-white/50">Importe os oito documentos atuais para iniciar a gestão.</div>}
  </div>;
}
