'use client';

import { BookOpenText, ChevronRight, Clock3, Disc3, Flame, Headphones, Library, ListMusic, Pause, Play, Radio, Settings2, SlidersHorizontal, Sparkles, Volume2, Waves, X } from 'lucide-react';
import Image from 'next/image';
import { useEffect, useMemo, useState } from 'react';

import { AudioReviewDrawer } from '@/features/sound/components/audio-review-drawer';
import { SoundPlaylistsPanel } from '@/features/sound/components/sound-playlists-panel';
import { SoundPomodoroPanel } from '@/features/sound/components/sound-pomodoro-panel';
import { SoundSettingsPanel } from '@/features/sound/components/sound-settings-panel';
import { officialSoundPresets } from '@/features/sound/presets';
import { useSound } from '@/features/sound/sound-provider';
import type { MixerChannelId, SoundPreset, SoundTrack } from '@/features/sound/types';
import { cn } from '@/lib/cn';

type Tab = 'discover' | 'library' | 'playlists' | 'mixer' | 'timer' | 'settings';

const channelDescriptions: Record<MixerChannelId, string> = { pink_noise: 'Equilíbrio amplo', brown_noise: 'Graves macios', rain_glass: 'Água no vidro', ocean_tide: 'Ondas lentas', fireplace: 'Crepitar contido', forest_night: 'Folhas e insetos', cafe_room: 'Sala distante', night_train: 'Trilhos amortecidos', typewriter_keys: 'Resposta às teclas' };
const waveform = [24, 52, 38, 76, 46, 84, 58, 32, 66, 92, 48, 72, 36, 62, 86, 44, 68, 28, 56, 78, 42, 64, 34, 50, 72, 30, 46, 60];

function channelIcon(id: MixerChannelId) { if (id === 'rain_glass' || id === 'ocean_tide') return Waves; if (id === 'fireplace') return Flame; if (id === 'typewriter_keys') return Sparkles; return Radio; }
function formatDuration(seconds: number) { const minutes = Math.floor(seconds / 60); return `${minutes}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`; }

export function SoundMegaMenu({ open, onClose, tracks }: { open: boolean; onClose: () => void; tracks: SoundTrack[] }) {
  const sound = useSound();
  const [tab, setTab] = useState<Tab>('discover');
  const [activePresetId, setActivePresetId] = useState('');
  const [genre, setGenre] = useState('Todos');
  const [reviewTrack, setReviewTrack] = useState<SoundTrack | null>(null);
  const activePreset = officialSoundPresets.find((preset) => preset.id === activePresetId);
  const genres = useMemo(() => ['Todos', ...Array.from(new Set([...officialSoundPresets.map((preset) => preset.genre), ...tracks.map((track) => track.genre).filter(Boolean)]))], [tracks]);
  const visiblePresets = genre === 'Todos' ? officialSoundPresets : officialSoundPresets.filter((preset) => preset.genre === genre);
  const visibleTracks = genre === 'Todos' ? tracks : tracks.filter((track) => track.genre === genre);

  useEffect(() => { if (!open) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [onClose, open]);
  if (!open) return null;

  async function applyPreset(preset: SoundPreset) { for (const channel of sound.channels) { const volume = preset.channels[channel.id]; sound.updateChannel(channel.id, { active: typeof volume === 'number', ...(typeof volume === 'number' ? { volumePercent: volume } : {}) }); } setActivePresetId(preset.id); await sound.startMixer(); }
  async function handleTrack(track: SoundTrack) { if (sound.currentTrack?.id === track.id) await sound.togglePlayback(); else await sound.playTrack(track); }

  const playingTitle = sound.currentTrack?.title ?? activePreset?.title ?? 'Mixagem da obra';
  const playingSubtitle = sound.currentTrack ? `${sound.currentTrack.authorName} · ${sound.currentTrack.genre}` : activePreset ? `${activePreset.genre} · ${activePreset.bpm} BPM` : `${sound.channels.filter((channel) => channel.active).length} camadas combinadas`;
  const cover = sound.currentTrack?.coverUrl || activePreset?.coverUrl || '/images/kit_marca/01_ilustracoes/escrita.svg';
  const hasSound = Boolean(sound.currentTrack || sound.mixerActive);

  return <div className="fixed inset-0 z-[90]" role="presentation"><button type="button" className="absolute inset-0 bg-ink/15 backdrop-blur-[2px]" onClick={onClose} aria-label="Fechar Som" /><section className="absolute left-1/2 top-[4.5rem] flex max-h-[min(49rem,calc(100dvh-5.5rem))] w-[min(76rem,calc(100vw-1.25rem))] -translate-x-1/2 flex-col overflow-hidden rounded-[1.75rem] border border-line-strong bg-surface shadow-floating" aria-label="Som da obra">
    <header className="flex items-center gap-4 border-b border-line px-5 py-3.5 sm:px-7"><span className="flex size-10 items-center justify-center rounded-full bg-accent text-on-accent"><Headphones className="size-4" /></span><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-accent">Autor Copilot Sound Lab</p><h2 className="truncate font-serif text-xl font-semibold text-ink">Som da obra</h2></div>{sound.pomodoroRunning && <button type="button" onClick={() => setTab('timer')} className="hidden rounded-full bg-accent-subtle px-3 py-1.5 text-xs font-semibold tabular-nums text-accent sm:block"><Clock3 className="mr-1.5 inline size-3.5" />{formatDuration(sound.pomodoroRemainingSeconds)}</button>}<button type="button" onClick={onClose} className="flex size-9 items-center justify-center rounded-full text-muted hover:bg-editor" aria-label="Fechar"><X className="size-4" /></button></header>
    {hasSound && <section className="border-b border-line bg-[linear-gradient(90deg,var(--surface-muted),var(--surface))] px-5 py-3 sm:px-7"><div className="flex items-center gap-3"><span className="relative size-12 shrink-0 overflow-hidden rounded-xl border border-line"><Image src={cover} alt="" fill unoptimized={cover.startsWith('http')} sizes="48px" className="object-cover" /></span><div className="min-w-0 w-48"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-accent">Em curso</p><strong className="block truncate text-sm text-ink">{playingTitle}</strong><span className="block truncate text-[10px] text-muted">{playingSubtitle}</span></div><div className="hidden h-10 min-w-0 flex-1 items-center gap-1 md:flex" aria-label="Visualizador da atmosfera">{waveform.map((height, index) => <span key={index} className={cn('min-w-0 flex-1 rounded-full bg-accent/35', (sound.playing || sound.mixerActive) && 'animate-pulse')} style={{ height: `${height}%`, animationDelay: `${index * 45}ms` }} />)}</div><label className="hidden items-center gap-2 lg:flex"><Volume2 className="size-3.5 text-muted" /><input aria-label="Volume" type="range" min={0} max={100} value={sound.volume} onChange={(event) => sound.setVolume(Number(event.target.value))} className="w-24 accent-accent" /></label><button type="button" onClick={() => void (sound.currentTrack ? sound.togglePlayback() : sound.toggleMixer())} className="flex size-11 shrink-0 items-center justify-center rounded-full bg-accent text-on-accent shadow-lg" aria-label="Pausar ou continuar">{sound.playing || sound.mixerActive ? <Pause className="size-4 fill-current" /> : <Play className="ml-0.5 size-4 fill-current" />}</button></div></section>}
    <div className="grid min-h-0 flex-1 md:grid-cols-[13rem_1fr]"><nav className="flex gap-1 overflow-x-auto border-b border-line bg-editor p-3 md:flex-col md:border-b-0 md:border-r" aria-label="Seções de som">{([['discover', Sparkles, 'Descobrir'], ['library', Library, 'Catálogo'], ['playlists', ListMusic, 'Playlists'], ['mixer', SlidersHorizontal, 'Mixer'], ['timer', Clock3, 'Pomodoro'], ['settings', Settings2, 'Configurações']] as const).map(([value, Icon, label]) => <button key={value} type="button" onClick={() => setTab(value)} className={cn('flex min-h-10 shrink-0 items-center gap-2 rounded-xl px-3 text-left text-xs font-semibold', tab === value ? 'bg-surface text-accent shadow-sm' : 'text-muted hover:bg-surface/60 hover:text-ink')}><Icon className="size-4" />{label}<ChevronRight className="ml-auto hidden size-3 md:block" /></button>)}</nav><div className="workspace-scrollbar min-h-0 overflow-y-auto p-5 sm:p-7">
      {tab === 'discover' && <><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-accent">Seleção oficial</p><h3 className="mt-1 font-serif text-3xl font-semibold text-ink">Escreva dentro de uma cena</h3><p className="mt-2 max-w-2xl text-sm text-muted">Sessões editoriais produzidas com as camadas nativas do Autor Copilot.</p></div><div className="flex max-w-full gap-1.5 overflow-x-auto">{genres.map((value) => <button key={value} type="button" onClick={() => setGenre(value)} className={cn('shrink-0 rounded-full px-3 py-1.5 text-[10px] font-semibold', genre === value ? 'bg-accent text-on-accent' : 'border border-line bg-editor text-muted')}>{value}</button>)}</div></div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visiblePresets.map((preset) => <article key={preset.id} className={cn('group overflow-hidden rounded-2xl border bg-surface transition-transform hover:-translate-y-0.5', activePresetId === preset.id ? 'border-accent' : 'border-line')}><button type="button" onClick={() => void applyPreset(preset)} className="relative block h-40 w-full overflow-hidden text-left"><Image src={preset.coverUrl} alt="" fill sizes="(min-width:1280px) 22vw, 45vw" className="object-cover transition-transform duration-500 group-hover:scale-[1.03]" /><span className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-transparent" /><span className="absolute left-3 top-3 rounded-md bg-black/55 px-2 py-1 text-[10px] font-bold text-white backdrop-blur">{preset.mood}</span><span className="absolute bottom-3 right-3 flex size-11 items-center justify-center rounded-full bg-accent text-on-accent shadow-lg">{activePresetId === preset.id && sound.mixerActive ? <Pause className="size-4 fill-current" /> : <Play className="ml-0.5 size-4 fill-current" />}</span></button><div className="p-4"><div className="flex items-center gap-2 text-[10px] text-muted"><span className="rounded-md bg-accent-subtle px-2 py-1 font-semibold text-accent">{preset.genre}</span><span>•</span><span>{preset.durationLabel}</span></div><h4 className="mt-2 font-serif text-xl leading-tight text-ink">{preset.title}</h4><p className="mt-1 line-clamp-2 text-xs leading-relaxed text-muted">{preset.description}</p><div className="mt-4 flex items-center justify-between border-t border-line pt-3 text-[10px] text-muted"><span><Headphones className="mr-1 inline size-3" />Áudio nativo</span><strong className="font-medium text-accent">{preset.bpm} BPM</strong></div></div></article>)}</div></>}
      {tab === 'library' && <><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-accent">Catálogos por gênero</p><h3 className="mt-1 font-serif text-3xl font-semibold text-ink">Faixas e audiolivros</h3></div><span className="text-xs text-muted">{visibleTracks.length} publicados</span></div><div className="mt-4 flex gap-1.5 overflow-x-auto">{genres.map((value) => <button key={value} type="button" onClick={() => setGenre(value)} className={cn('shrink-0 rounded-full px-3 py-1.5 text-[10px] font-semibold', genre === value ? 'bg-accent text-on-accent' : 'border border-line bg-editor text-muted')}>{value}</button>)}</div>{visibleTracks.length ? <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visibleTracks.map((track) => <article key={track.id} className="overflow-hidden rounded-2xl border border-line bg-surface"><button type="button" onClick={() => void handleTrack(track)} className="relative block h-36 w-full overflow-hidden bg-accent-subtle">{track.coverUrl ? <Image src={track.coverUrl} alt="" fill unoptimized sizes="30vw" className="object-cover" /> : <Image src="/images/kit_marca/01_ilustracoes/escrita.svg" alt="" fill sizes="30vw" className="object-cover" />}<span className="absolute bottom-3 right-3 flex size-10 items-center justify-center rounded-full bg-accent text-on-accent">{sound.currentTrack?.id === track.id && sound.playing ? <Pause className="size-3.5 fill-current" /> : <Play className="ml-0.5 size-3.5 fill-current" />}</span></button><div className="p-4"><span className="rounded-md bg-accent-subtle px-2 py-1 text-[10px] font-semibold text-accent">{track.genre}</span><h4 className="mt-2 truncate font-serif text-xl text-ink">{track.title}</h4><p className="mt-1 truncate text-xs text-muted">{track.authorName}</p><div className="mt-3 flex items-center justify-between border-t border-line pt-3 text-[10px] text-muted"><span>{track.mood || track.tags[0] || 'Editorial'}</span><span>{track.mentalRhythmBpm} BPM</span></div>{track.kind === 'audiobook' && <button type="button" onClick={() => setReviewTrack(track)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-line py-2 text-xs font-semibold text-accent"><BookOpenText className="size-3.5" />Abrir prova editorial</button>}</div></article>)}</div> : <div className="mt-6 rounded-2xl border border-dashed border-line bg-editor p-8"><Disc3 className="size-6 text-accent" /><h4 className="mt-3 font-serif text-xl text-ink">Nenhuma faixa neste gênero</h4><p className="mt-2 text-sm text-muted">As sessões nativas continuam disponíveis em Descobrir.</p></div>}</>}
      {tab === 'playlists' && <SoundPlaylistsPanel tracks={tracks} />}
      {tab === 'mixer' && <><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-accent">Mesa da obra</p><h3 className="mt-1 font-serif text-3xl font-semibold text-ink">Misture o seu lugar</h3></div><button type="button" onClick={() => void sound.toggleMixer()} className={cn('inline-flex min-h-10 items-center justify-center gap-2 rounded-full px-4 text-xs font-semibold', sound.mixerActive ? 'border border-line bg-editor text-ink' : 'bg-accent text-on-accent')}>{sound.mixerActive ? <Pause className="size-3.5" /> : <Play className="size-3.5" />}{sound.mixerActive ? 'Pausar atmosfera' : 'Ouvir mixagem'}</button></div><div className="mt-6 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{sound.channels.map((channel) => { const Icon = channelIcon(channel.id); return <article key={channel.id} className={cn('rounded-2xl border p-4', channel.active ? 'border-accent/25 bg-accent-subtle' : 'border-line bg-editor')}><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-surface text-accent"><Icon className="size-4" /></span><span className="min-w-0 flex-1"><strong className="block text-sm text-ink">{channel.label}</strong><span className="text-[10px] text-muted">{channelDescriptions[channel.id]}</span></span><input aria-label={`Ativar ${channel.label}`} type="checkbox" checked={channel.active} onChange={(event) => sound.updateChannel(channel.id, { active: event.target.checked })} className="accent-accent" /></div><label className="mt-4 flex items-center gap-3"><Volume2 className="size-3.5 text-muted" /><input aria-label={`Volume de ${channel.label}`} type="range" min={0} max={100} value={channel.volumePercent} onChange={(event) => sound.updateChannel(channel.id, { volumePercent: Number(event.target.value) })} className="min-w-0 flex-1 accent-accent" /><span className="w-8 text-right text-[10px] tabular-nums text-muted">{channel.volumePercent}</span></label></article>; })}</div></>}
      {tab === 'timer' && <SoundPomodoroPanel />}
      {tab === 'settings' && <SoundSettingsPanel />}
    </div></div><AudioReviewDrawer track={reviewTrack} onClose={() => setReviewTrack(null)} />
  </section></div>;
}
