import { Flag, Save } from 'lucide-react';

import { PendingSubmitButton } from '@/components/ui';
import { updateFeatureFlag } from '@/features/admin/actions/product-controls';
import { requireAdmin } from '@/features/admin/auth';
import { createAdminClient } from '@/lib/supabase/admin';

export default async function AdminFlagsPage() {
  await requireAdmin('features.read');
  const supabase = createAdminClient();
  const { data: flags, error } = await supabase.from('feature_flags').select('*').order('key');
  return <div><p className="text-xs uppercase tracking-[0.2em] text-accent">Distribuição controlada</p><h1 className="mt-2 text-3xl font-semibold">Feature flags e tags</h1><p className="mt-3 text-sm text-muted">Controle ativação, rollout gradual e segmentos autorizados.</p>{error ? <p className="mt-7 rounded-control border border-amber-400/20 bg-amber-400/10 p-4 text-warning">As tabelas administrativas ainda não existem no Supabase conectado. Execute <code className="rounded bg-surface-muted px-1.5 py-0.5">npx supabase db push</code> após autenticar a CLI. {error.message}</p> : <div className="mt-7 grid gap-4 lg:grid-cols-2">{(flags ?? []).map((flag) => <form key={flag.key} action={updateFeatureFlag} className="rounded-card border border-line bg-surface p-5"><input type="hidden" name="key" value={flag.key} /><div className="flex items-start gap-3"><Flag className="mt-0.5 size-5 text-accent" /><div><h2 className="font-medium">{flag.name}</h2><code className="text-[10px] text-muted">{flag.key}</code></div><label className="ml-auto flex items-center gap-2 text-xs text-muted"><input name="enabled" type="checkbox" defaultChecked={flag.enabled} />Ativa</label></div><p className="mt-3 text-sm text-muted">{flag.description}</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-xs text-muted">Rollout %<input name="rollout_percentage" type="number" min="0" max="100" defaultValue={flag.rollout_percentage} className="mt-1.5 min-h-10 w-full rounded-control border border-line bg-editor px-3 text-ink" /></label><label className="text-xs text-muted">Grupos<input name="allowed_groups" defaultValue={flag.allowed_groups.join(', ')} className="mt-1.5 min-h-10 w-full rounded-control border border-line bg-editor px-3 text-ink" /></label><label className="text-xs text-muted">Tags<input name="tags" defaultValue={flag.tags.join(', ')} className="mt-1.5 min-h-10 w-full rounded-control border border-line bg-editor px-3 text-ink" /></label></div><PendingSubmitButton pendingLabel="Salvando flag…" className="mt-4 min-h-10 rounded-control bg-accent text-on-accent px-3 text-sm font-medium hover:bg-accent-hover"><Save className="size-4" />Salvar flag</PendingSubmitButton></form>)}</div>}</div>;
}
