'use client';
import { useState } from 'react';
import { BookOpenText, MapPin, Plus, Search, UserRound, X } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';

type Entry = { id: number; name: string; type: string; detail: string };
export const initialEntries: Entry[] = [{ id: 1, name: 'Aurora', type: 'Personagem', detail: 'Cartógrafa da costa do norte. Procura nas cartas um caminho de volta.' }, { id: 2, name: 'Farol do norte', type: 'Lugar', detail: 'A última luz antes do mar aberto. Guarda cartas que nunca foram enviadas.' }, { id: 3, name: 'A carta', type: 'Objeto', detail: 'Um envelope marcado pela maré. A caligrafia parece familiar.' }];

export function AtlasEncyclopedia({ entries, onCreate }: { entries: Entry[]; onCreate: (entry: Entry) => void }) {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('Todas');
  const [open, setOpen] = useState(false);
  const [selected, setSelected] = useState<Entry | null>(null);
  const filtered = entries.filter((entry) => (category === 'Todas' || entry.type === category) && `${entry.name} ${entry.detail}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <div className="ac-atlas-library"><div className="ac-atlas-library-heading"><div><span className="ac-eyebrow">O atlas das marés / Universo</span><h2>Enciclopédia</h2><p>Cada detalhe tem uma história.</p></div><button className="ac-button" onClick={() => setOpen(true)}><Plus size={15} />Criar ficha</button></div><div className="ac-atlas-filters"><label><Search size={15} /><input aria-label="Buscar fichas da demonstração" placeholder="Procure uma ideia, um nome…" value={query} onChange={(event) => setQuery(event.target.value)} /></label><div>{['Todas', 'Personagem', 'Lugar', 'Objeto'].map((type) => <button key={type} aria-pressed={category === type} onClick={() => setCategory(type)}>{type}</button>)}</div></div><div className="ac-atlas-cards">{filtered.map((entry) => <button key={entry.id} onClick={() => setSelected(entry)} className="ac-atlas-entry"><span className={`ac-atlas-entry-art type-${entry.type}`}>{entry.type === 'Personagem' ? <UserRound size={32} /> : entry.type === 'Lugar' ? <MapPin size={32} /> : <BookOpenText size={32} />}</span><small>{entry.type}</small><strong>{entry.name}</strong><p>{entry.detail}</p><span className="ac-atlas-open">Abrir ficha ↗</span></button>)}</div>{!filtered.length && <p className="ac-atlas-empty">Nenhuma ficha encontrada. Experimente outro nome ou crie uma ficha.</p>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="ac-atlas-drawer !bg-surface !text-ink !border-line" showCloseButton={false}><div className="flex items-center justify-between"><DialogTitle className="font-serif text-2xl">Registrar no universo</DialogTitle><button aria-label="Fechar criação de ficha" onClick={() => setOpen(false)}><X size={19} /></button></div><DialogDescription className="!text-muted">Crie uma ficha de exemplo. Ela também aparecerá no grafo durante esta visita.</DialogDescription><form className="ac-atlas-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onCreate({ id: Date.now(), name: String(form.get('name')).trim(), type: String(form.get('type')), detail: String(form.get('detail')).trim() }); setOpen(false); }}><label htmlFor="atlas-entry-name">Nome<input id="atlas-entry-name" name="name" required maxLength={60} placeholder="Como se chama?" /></label><label htmlFor="atlas-entry-type">Tipo<select id="atlas-entry-type" name="type" aria-label="Tipo"><option>Personagem</option><option>Lugar</option><option>Objeto</option></select></label><label htmlFor="atlas-entry-detail">O que torna esta ficha importante?<textarea id="atlas-entry-detail" name="detail" required maxLength={240} placeholder="Um desejo, um segredo, uma memória…" rows={4} /></label><button className="ac-button" type="submit">Adicionar ao universo <Plus size={15} /></button></form></DialogContent></Dialog>
    <Dialog open={Boolean(selected)} onOpenChange={(value) => { if (!value) setSelected(null); }}><DialogContent className="!bg-surface !text-ink !border-line" showCloseButton={false}><span className="ac-eyebrow">{selected?.type}</span><DialogTitle className="font-serif text-3xl">{selected?.name}</DialogTitle><DialogDescription className="!text-muted">{selected?.detail}</DialogDescription><button className="ac-button-secondary" onClick={() => setSelected(null)}>Voltar às fichas</button></DialogContent></Dialog>
  </div>;
}

export function AtlasGraph({ entries }: { entries: Entry[] }) {
  const [selected, setSelected] = useState<number | null>(null);
  const [linked, setLinked] = useState<number[]>([1, 2, 3]);
  const entry = entries.find((item) => item.id === selected);
  return <div className="ac-atlas-graph-layout"><div className="ac-atlas-graph"><div className="ac-atlas-graph-caption"><span className="ac-eyebrow">Mapa do universo</span><h2>Uma história feita de relações.</h2></div><div className="ac-graph-map"><svg viewBox="0 0 600 350" preserveAspectRatio="none" aria-hidden="true">{entries.slice(0, 8).map((item, i, all) => { const angle = i / all.length * Math.PI * 2 - Math.PI / 2; return linked.includes(item.id) ? <line key={item.id} x1="300" y1="175" x2={300 + Math.cos(angle) * 210} y2={175 + Math.sin(angle) * 125} /> : null; })}</svg><span className="ac-graph-center"><BookOpenText size={22} />O atlas das marés<small>OBRA / UNIVERSO</small></span>{entries.slice(0, 8).map((item, i, all) => { const angle = i / all.length * Math.PI * 2 - Math.PI / 2; return <button key={item.id} style={{ left: `${50 + Math.cos(angle) * 35}%`, top: `${50 + Math.sin(angle) * 36}%` }} aria-pressed={selected === item.id} onClick={() => setSelected(item.id)}><span>{item.type}</span>{item.name}</button>; })}</div></div><aside className="ac-graph-inspector"><span className="ac-eyebrow">Explore uma conexão</span><h3>{entry?.name ?? 'Nada existe sozinho.'}</h3><p>{entry?.detail ?? 'Selecione um nó para consultar a ficha e experimentar os vínculos com a obra.'}</p>{entry && <button className="ac-button-secondary" onClick={() => setLinked(linked.includes(entry.id) ? linked.filter((id) => id !== entry.id) : [...linked, entry.id])}>{linked.includes(entry.id) ? 'Remover vínculo' : 'Conectar à obra'}</button>}<small>{linked.filter((id) => entries.some((item) => item.id === id)).length} vínculos no exemplo · até 8 fichas visíveis</small></aside></div>;
}

