export const publicPages = {
  funcionalidades: { title: 'Uma história inteira. Um lugar para criar.', eyebrow: 'Conheça o produto', description: 'Da primeira ideia à organização do seu universo, ferramentas que acompanham o seu processo.', cards: [ ['Editor e manuscrito', 'Capítulos, cenas, notas, modo foco e configurações de página para encontrar seu ritmo.'], ['Enciclopédia viva', 'Fichas de personagens, lugares e outros elementos, com campos próprios para cada tipo.'], ['Referências com @', 'Vincule o texto às fichas do universo e consulte referências sem perder o contexto.'], ['Projetos e universos', 'Organize obras que compartilham um mesmo mundo e explore suas relações.'], ['Media & Sound', 'Combine ambientes sonoros e organize sessões de escrita dentro do workspace.'], ['Extensões oficiais', 'Escolha as ferramentas do Autor Copilot Lab disponíveis para sua conta.'] ] },
  'como-funciona': { title: 'Seu próximo capítulo começa com três passos.', eyebrow: 'Do começo ao seu ritmo', description: 'Você pode começar pequeno. A estrutura cresce junto com a história.', cards: [ ['01 · Crie sua obra', 'Dê um nome ao projeto e abra seu primeiro capítulo. Você pode ajustar os fundamentos depois.'], ['02 · Escreva e conecte', 'Crie fichas na Enciclopédia e use a extensão @ para conectá-las ao manuscrito.'], ['03 · Organize e continue', 'Revise as referências, consulte as relações e acompanhe o progresso da obra.'] ] },
  guias: { title: 'Uma boa ferramenta também ensina o caminho.', eyebrow: 'Guias de escrita', description: 'Roteiros práticos para conhecer o Autor Copilot, um passo de cada vez.', cards: [ ['Seu primeiro capítulo', 'Crie uma conta, abra o ambiente de escrita, escolha uma obra e escreva no Editor. O manuscrito reúne capítulos, cenas e notas.'], ['Sua primeira ficha', 'Abra a Enciclopédia e selecione Criar ficha. Escolha o tipo, preencha os campos relevantes e salve. Você pode aprofundar depois.'], ['Conecte com @', 'Ative a extensão de referências na sua conta. No manuscrito, digite @, procure uma ficha e selecione o resultado para inserir o vínculo.'], ['Planeje os fundamentos', 'Na Enciclopédia, abra a jornada dos fundamentos. Escolha o nível de personalização e responda às perguntas; as escolhas continuam editáveis.'], ['Crie um ambiente sonoro', 'Acesse Som no workspace. Escolha um ambiente, ajuste os volumes e salve a combinação disponível para sua sessão.'], ['Encontre ajuda', 'Consulte os guias do produto nas telas e a central de ajuda para conteúdos publicados pela equipe.'] ] },
  documentacao: { title: 'Entenda como seu espaço se organiza.', eyebrow: 'Documentação do produto', description: 'Os conceitos essenciais para trabalhar com histórias conectadas.', cards: [ ['Projeto', 'O contexto de organização do trabalho criativo. Reúne o planejamento e as obras relacionadas.'], ['Universo', 'O mundo narrativo compartilhado: pessoas, lugares, regras e relações que dão continuidade às obras.'], ['Obra e manuscrito', 'A obra contém os documentos de escrita. Capítulos, cenas e notas ajudam a separar conteúdo e planejamento.'], ['Ficha e referência', 'A ficha registra um elemento da Enciclopédia; a referência @ conecta uma menção no texto a esse registro.'], ['Extensão', 'Uma ferramenta opcional. Sua disponibilidade depende da ativação, aquisição ou liberação para a conta.'], ['Publicação oficial', 'Conteúdos aprovados pela equipe são distribuídos nos catálogos de ajuda, atualizações, comunicados e documentos legais.'] ] },
  sobre: { title: 'A história é sua. O espaço acompanha.', eyebrow: 'Autor Copilot', description: 'Construímos um ambiente editorial para quem pensa em personagens por dias e em universos por anos.', cards: [ ['Autoria no centro', 'Ferramentas para apoiar decisões criativas, organizar ideias e dar espaço à escrita.'], ['Continuidade com contexto', 'Manuscrito e conhecimento do universo próximos, para que cada referência tenha um lugar.'], ['Evolução transparente', 'As mudanças do produto e os comunicados oficiais ficam disponíveis nos nossos catálogos públicos.'] ] },
  contato: { title: 'Vamos encontrar o caminho certo.', eyebrow: 'Contato e suporte', description: 'Escolha o assunto para acessar as informações e os canais disponíveis.', cards: [ ['Ajuda com o produto', 'Consulte a central de ajuda e os guias de primeiros passos.', '/ajuda'], ['Conta e preferências', 'Entre na sua conta para consultar e editar os dados e preferências.', '/account'], ['Privacidade e dados', 'Os documentos legais informam os direitos e os canais de contato responsáveis.', '/legal/privacidade'], ['Comunicados oficiais', 'Acompanhe orientações e anúncios publicados pela equipe.', '/comunicados'] ] },
  comunidade: { title: 'Histórias crescem quando ideias se encontram.', eyebrow: 'Comunidade', description: 'Este é o ponto de encontro para acompanhar as iniciativas do Autor Copilot.', cards: [ ['Conteúdo editorial', 'Explore os textos publicados no blog oficial.', '/blog'], ['Cartas do Autor Copilot', 'Leia as edições públicas da nossa newsletter.', '/newsletters'], ['Iniciativas e encontros', 'Novos programas serão anunciados nos comunicados oficiais. Não há inscrição aberta nesta página.', '/comunicados'] ] },
  carreiras: { title: 'Construir ferramentas para quem cria.', eyebrow: 'Carreiras', description: 'Quando houver oportunidades abertas, elas serão divulgadas nos canais oficiais.', cards: [ ['Oportunidades', 'Nenhuma vaga está anunciada nesta página neste momento. Acompanhe os comunicados para novas publicações.', '/comunicados'], ['Conheça o produto', 'Escrita, organização de universos e experiência editorial são parte do que construímos.', '/sobre'] ] },
  imprensa: { title: 'Autor Copilot, em poucas palavras.', eyebrow: 'Imprensa', description: 'Informações institucionais para conhecer e apresentar o produto.', cards: [ ['Apresentação', 'Autor Copilot é um ambiente de escrita que reúne manuscritos, fichas de universo, referências e ferramentas opcionais de apoio ao autor.'], ['Publicações oficiais', 'Consulte anúncios e informações publicadas pela equipe.', '/comunicados'], ['Marca e contato', 'Para orientações de uso da marca e contato institucional, consulte os canais oficiais.', '/contato'] ] },
  roadmap: { title: 'Acompanhe a próxima versão da sua ferramenta.', eyebrow: 'Evolução do produto', description: 'Conheça o que já foi publicado e os próximos anúncios oficiais.', cards: [ ['Já entregue', 'O catálogo de atualizações reúne versões e notas publicadas pela equipe.', '/updates'], ['Próximos passos', 'Planos e mudanças futuras serão comunicados quando estiverem confirmados. Não publicamos prazos estimados como compromissos.', '/comunicados'], ['Recursos atuais', 'Veja as principais áreas do ambiente de escrita.', '/funcionalidades'] ] },
} as const;

export const footerGroups = [
  { title: 'Produto', links: [['Funcionalidades', '/funcionalidades'], ['Como funciona', '/como-funciona'], ['Preços', '/precos'], ['Roadmap', '/roadmap'], ['Status', '/status']] },
  { title: 'Recursos', links: [['Blog', '/blog'], ['Documentação', '/documentacao'], ['Guias', '/guias'], ['Ajuda', '/ajuda'], ['Comunidade', '/comunidade'], ['Atualizações', '/updates']] },
  { title: 'Empresa', links: [['Sobre', '/sobre'], ['Contato', '/contato'], ['Carreiras', '/carreiras'], ['Imprensa', '/imprensa'], ['Publicações', '/publicacoes']] },
  { title: 'Transparência', links: [['Documentos legais', '/legal'], ['Privacidade e dados', '/legal/privacidade'], ['Cookies', '/cookies'], ['Comunicados', '/comunicados'], ['Newsletters', '/newsletters']] },
];

export const faqs = [
  ['Como começo?', 'Crie sua conta e abra o ambiente de escrita. Comece com um capítulo e acrescente fichas e ferramentas conforme precisar.'],
  ['A IA escreve ou altera meu texto sozinha?', 'A proposta é manter o autor no controle. As ferramentas de apoio são opcionais e sua disponibilidade depende das extensões habilitadas.'],
  ['Como funcionam as referências @?', 'Com a extensão habilitada, selecione uma ficha ao digitar @ no editor. A referência mantém a conexão entre o manuscrito e a Enciclopédia.'],
  ['Posso editar os fundamentos depois?', 'Sim. A jornada ajuda a organizar as primeiras decisões, mas você pode revisar as configurações da obra.'],
  ['Funciona sem internet?', 'O editor possui estados de salvamento local e sincronização. Acesse a plataforma com conexão e confira o indicador de salvamento antes de fechar; não há garantia de acesso completo offline.'],
  ['Onde vejo o que está incluso na minha conta?', 'Na área de conta e no catálogo de extensões. Ativação e disponibilidade são verificadas para cada usuário.'],
  ['Como meus dados são tratados?', 'Consulte a política de privacidade e os documentos legais para conhecer o tratamento dos dados e os canais de atendimento.'],
  ['Posso mudar minhas preferências de cookies?', 'Sim. Use Preferências de cookies no rodapé a qualquer momento. Cookies opcionais começam desativados.'],
];
