import Link from 'next/link';
import Image from 'next/image';
import { ArrowDown, ArrowUpRight, BookOpenText, Feather, Headphones, Library, Network, NotebookPen, Sparkles } from 'lucide-react';
import { footerGroups } from './catalog';
import { openCookiePreferences } from './cookie-preferences';

const product = [
  ['Manuscrito', 'O texto no centro de tudo.', '/demo?view=manuscrito', NotebookPen],
  ['Enciclopédia', 'Dê profundidade ao seu mundo.', '/demo?view=enciclopedia', Library],
  ['Universos e relações', 'Veja o que conecta sua história.', '/demo?view=universo', Network],
  ['Referências @', 'Uma menção, todo um contexto.', '/funcionalidades', Sparkles],
  ['Media & Sound', 'Encontre o som da sua sessão.', '/funcionalidades', Headphones],
  ['Modo foco', 'Espaço para o próximo parágrafo.', '/como-funciona', Feather],
] as const;

export function EditorialMenu({ index }: { index: number }) {
  if (index === 0) return <div className="ac-menu-product"><div><span className="ac-menu-kicker">01 / O ESTÚDIO</span><div className="ac-menu-product-grid">{product.map(([title, desc, href, Icon], i) => <Link href={href} key={title} style={{ animationDelay: `${i * 35}ms` }}><Icon size={19} /><span><strong>{title}</strong><small>{desc}</small></span><ArrowUpRight size={14} /></Link>)}</div><div className="ac-menu-bottom"><Link href="/funcionalidades">Todas as funcionalidades <ArrowUpRight size={14} /></Link><Link href="/precos">Planos e possibilidades</Link></div></div><Link href="/demo" className="ac-menu-feature"><span className="ac-eyebrow">Entre. Explore. Imagine.</span><div className="ac-mini-manuscript"><small>CAPÍTULO I</small><h3>A casa do farol</h3><p>O mar devolvia tudo,<br />menos as respostas.</p><span>@Aurora</span></div><strong>Um estúdio para chamar de seu.<ArrowUpRight size={18} /></strong></Link></div>;
  if (index === 1) return <div className="ac-menu-resources"><div className="ac-menu-reading"><span className="ac-menu-kicker">02 / CADERNO DE LEITURA</span><h2>Ideias para<br /><em>seguir escrevendo.</em></h2><p>Entre uma dúvida e uma descoberta, há sempre um próximo passo.</p><Link href="/blog">Abrir a revista <ArrowUpRight size={16} /></Link></div><div className="ac-menu-resource-list">{[['Guias', 'Um primeiro capítulo, uma primeira ficha.', '/guias'], ['Documentação', 'Conheça as peças do seu universo.', '/documentacao'], ['Central de ajuda', 'Respostas para continuar criando.', '/ajuda'], ['Cartas', 'O arquivo editorial do Autor Copilot.', '/newsletters']].map(([name, text, href], i) => <Link key={href} href={href}><span>0{i + 1}</span><div><strong>{name}</strong><small>{text}</small></div><ArrowUpRight size={16} /></Link>)}</div><div className="ac-menu-resource-extra"><span className="ac-eyebrow">Nos bastidores</span><Link href="/updates">Diário de atualizações <ArrowUpRight size={15} /></Link><Link href="/roadmap">O que vem pela frente <ArrowUpRight size={15} /></Link><Link href="/comunidade">Comunidade <ArrowUpRight size={15} /></Link><Link href="/status">Status dos serviços <ArrowUpRight size={15} /></Link></div></div>;
  return <div className="ac-menu-company"><div className="ac-menu-company-art"><Image src="/images/editorial/universo-aquarela.png" alt="Um farol nasce das páginas de um livro em aquarela" width={600} height={400} /><span>Histórias merecem um lugar.</span></div><div><span className="ac-menu-kicker">03 / QUEM ESTÁ POR AQUI</span><div className="ac-menu-company-links">{[['Nossa história', '/sobre'], ['Fale com a gente', '/contato'], ['Carreiras', '/carreiras'], ['Imprensa', '/imprensa'], ['Publicações oficiais', '/publicacoes'], ['Privacidade e confiança', '/legal']].map(([label, href]) => <Link href={href} key={href}>{label}<ArrowUpRight size={16} /></Link>)}</div></div></div>;
}

export function EditorialFooter() {
  return <footer className="ac-editorial-footer"><div className="ac-footer-prologue"><span className="ac-eyebrow">Toda história pede uma continuação.</span><Link href="/register" className="ac-footer-big-link">A sua começa <em>aqui.</em><ArrowUpRight aria-hidden="true" /></Link><div className="ac-footer-prologue-bottom"><p>Um lugar para o rascunho.<br />Espaço para tudo o que ele pode se tornar.</p><Link className="ac-button" href="/register">Abrir meu espaço <ArrowUpRight size={16} /></Link></div></div><div className="ac-footer-directory"><div className="ac-footer-colophon"><BookOpenText size={32} /><span>Autor Copilot</span><p>Ferramentas para escrever.<br />Liberdade para imaginar.</p><Link href="/newsletters">Correspondências do estúdio <ArrowUpRight size={14} /></Link></div>{footerGroups.map((group, index) => <div key={group.title}><span className="ac-menu-kicker">0{index + 1} / {group.title}</span>{group.links.map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</div>)}</div><div className="ac-footer-signature" aria-hidden="true">autor<span>copilot</span><Feather /></div><div className="ac-footer-bottom"><span>© {new Date().getFullYear()} Autor Copilot</span><button onClick={openCookiePreferences}>Suas preferências de cookies</button><a href="#public-content">Voltar ao início <ArrowDown size={13} className="rotate-180" /></a></div></footer>;
}
