import Link from 'next/link';
import Image from 'next/image';
import { EditorialMotion, ScrollText, SplitTitle } from './editorial-motion';
import { ArrowRight, ArrowUpRight, BookOpenText, Check, Focus, Link2, Network, NotebookPen, ShieldCheck, Volume2 } from 'lucide-react';
import { faqs } from './catalog';
import { ProductDemo } from './demo';

export function FAQ() {
  return <section id="faq" className="ac-section ac-faq"><div><span className="ac-eyebrow">Antes do primeiro capítulo</span><h2>Algumas respostas.<br />Mais espaço para criar.</h2><p>Mais orientações na <Link href="/ajuda">central de ajuda</Link>.</p></div><div>{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>;
}

export function Landing() {
  return <EditorialMotion><main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@graph': [{ '@type': 'SoftwareApplication', name: 'Autor Copilot', applicationCategory: 'ProductivityApplication', operatingSystem: 'Web', description: 'Ambiente de escrita com manuscrito, fichas e referências conectadas.' }, { '@type': 'Organization', name: 'Autor Copilot' }, { '@type': 'FAQPage', mainEntity: faqs.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })) }] }).replace(/</g, '\\u003c') }} />
    <section className="ac-editorial-hero">
      <div className="ac-hero-folio"><span>O ESTÚDIO LITERÁRIO / AUTOR COPILOT</span><Link href="/updates">Caderno de novidades <ArrowUpRight size={13} /></Link></div>
      <div className="ac-editorial-hero-grid"><div className="ac-editorial-hero-copy"><span className="ac-eyebrow">Para quem tem um mundo por dentro.</span><SplitTitle lines={['Uma história.', 'Infinitas', 'possibilidades.']} /><p>Escreva com espaço para imaginar.<br />Conecte tudo o que faz o seu universo existir.</p><div className="ac-hero-actions"><Link href="/register" className="ac-button">Começar minha história <ArrowUpRight size={17} /></Link><Link href="#demonstracao" className="ac-editorial-underlink">Entre no estúdio <ArrowRight size={16} /></Link></div><span className="ac-hero-note">O texto é seu. O ritmo também.</span></div><figure className="ac-watercolor-hero" data-parallax="-100"><Image src="/images/editorial/universo-aquarela.png" alt="Das páginas de um manuscrito nasce um farol cercado pelo mar, em aquarela" width={1536} height={1024} sizes="(max-width: 760px) 100vw, 65vw" priority /><figcaption>FIG. 01 — TODO UNIVERSO COMEÇA EM UMA PÁGINA.</figcaption><span className="ac-art-margin" aria-hidden="true">imaginar é um começo.</span></figure></div><div className="ac-hero-end"><span>Escrita / Contexto / Continuidade</span><a href="#manifesto">Continue a história ↓</a><span>01 — 05</span></div>
    </section>
    <section id="manifesto" className="ac-manifesto"><span className="ac-eyebrow">01 / Mais do que palavras</span><ScrollText text="Você não está apenas escrevendo um livro. Está construindo um mundo que ainda não existe. Dê a ele espaço para acontecer." /><div><span>Uma ideia encontra outra.</span><p>Manuscrito, fichas e relações próximos.<br />Para que você possa ir mais longe.</p></div></section>
    <section className="ac-studio-intro" data-reveal><span className="ac-eyebrow">02 / Abra as portas do estúdio</span><h2>Entre o que você imagina<br /><em>e o que você escreve.</em></h2><p>Uma prévia interativa inspirada no seu ambiente de escrita.<br />Explore o manuscrito, crie uma ficha, conecte o universo.</p></section>
    <section id="demonstracao" className="ac-hero-demo ac-editorial-stage" data-scroll-stage><div className="ac-stage-sticky"><ProductDemo /></div><div className="ac-product-strip"><span>DO PRIMEIRO RASCUNHO AO UNIVERSO INTEIRO</span><span><NotebookPen size={17} /> Escrever</span><span><BookOpenText size={17} /> Organizar</span><span><Network size={17} /> Conectar</span><span><Focus size={17} /> Continuar</span></div></section>
    <section className="ac-section ac-problem" data-reveal><div className="ac-section-heading" data-reveal><span className="ac-eyebrow">Sua cabeça já tem um universo</span><h2>Ele não precisa ficar<br />espalhado em mil lugares.</h2><p>Uma nota perdida. Um nome que mudou. Uma ideia que ficou em outra aba. Traga o contexto para perto da escrita.</p></div><div className="ac-three-cards">{[['01', 'Onde eu anotei isso?', 'Dê a personagens, lugares e ideias um endereço na Enciclopédia.'], ['02', 'Esse nome mudou.', 'Conecte menções a fichas com a extensão @ e encontre suas referências.'], ['03', 'Por onde continuo?', 'Reúna capítulos, cenas e notas na estrutura da obra.']].map(([n, title, text]) => <article key={n} data-reveal><span className="ac-card-number">{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="funcionalidades" className="ac-section"><div className="ac-section-heading" data-reveal><span className="ac-eyebrow">Tudo conversa com a sua história</span><h2>Um lugar para o texto.<br /><em>E tudo que vive ao redor dele.</em></h2><p>Ferramentas próximas quando você precisa. Espaço livre quando é hora de escrever.</p></div><div className="ac-bento"><article className="ac-bento-main" data-parallax="-45"><Link2 /><span className="ac-eyebrow">Referências inteligentes</span><h3>Um @.<br />Toda uma história por trás.</h3><p>Conecte personagens e lugares ao manuscrito. Acesse o contexto sem perder o fio da narrativa.</p><div className="ac-reference-art"><span>“Quando <b>@Aurora</b> voltou ao farol…”</span><div><i>A</i><strong>Aurora<small>Personagem · Cartógrafa</small></strong><Check size={17} /></div></div><Link href="/demo">Experimente a conexão <ArrowUpRight size={15} /></Link></article><article><Network /><h3>Universos com estrutura.</h3><p>Projetos, obras e fichas relacionados em um mesmo contexto.</p><div className="ac-node-art" aria-hidden="true"><span>Obra</span><i /><span>Universo</span><i /><span>Fichas</span></div></article><article><Focus /><h3>Só você e o próximo parágrafo.</h3><p>Modo foco e um canvas que dá espaço para o texto respirar.</p><div className="ac-lines-art" aria-hidden="true"><i /><i /><i /><i /></div></article><article><BookOpenText /><h3>Personagens além do nome.</h3><p>Fichas específicas e uma jornada para construir os fundamentos da obra.</p><Link href="/guias">Conhecer os guias <ArrowUpRight size={14} /></Link></article><article><Volume2 /><h3>O som do seu processo.</h3><p>Ambientes e mixagem integrados ao workspace, para acompanhar a sessão.</p><div className="ac-wave-art" aria-hidden="true">{Array.from({ length: 20 }, (_, i) => <i key={i} style={{ height: `${12 + ((i * 17) % 36)}px` }} />)}</div></article></div></section>
    <section id="como-funciona" className="ac-section ac-steps"><div><span className="ac-eyebrow">Sem precisar ter tudo pronto</span><h2>Comece com uma ideia.<br />O resto ganha forma.</h2><Link className="ac-text-link" href="/como-funciona">Veja como funciona <ArrowRight size={16} /></Link></div><ol>{[['Crie sua obra', 'Um título provisório já basta. Abra espaço para o primeiro capítulo.'], ['Escreva e conecte', 'Registre ideias e crie fichas conforme a história pede.'], ['Encontre seu ritmo', 'Organize o manuscrito e volte com o contexto por perto.']].map(([title, text], i) => <li key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section>
    <section className="ac-section"><div className="ac-section-heading" data-reveal><span className="ac-eyebrow">Não existe um único jeito de escrever</span><h2>Qual é a sua próxima história?</h2></div><div className="ac-three-cards ac-personas">{[['Seu primeiro livro', 'Ideias ganham estrutura, sem exigir que você planeje tudo antes de começar.'], ['Uma série inteira', 'Organize fichas e relações de um universo que atravessa mais de uma obra.'], ['Um mundo em construção', 'Explore lugares, personagens e fundamentos antes de escrever a primeira cena.']].map(([title, text]) => <article key={title}><BookOpenText size={26} /><h3>{title}</h3><p>{text}</p><Link href="/guias">Encontre seu começo <ArrowUpRight size={14} /></Link></article>)}</div></section>
    <section id="precos" className="ac-section ac-pricing-teaser"><ShieldCheck size={32} /><span className="ac-eyebrow">Escolhas transparentes</span><h2>Um espaço que acompanha<br />a sua fase de criação.</h2><p>Conheça a proposta dos planos e consulte as condições disponíveis na sua conta. Ferramentas e extensões têm sua disponibilidade indicada no catálogo.</p><Link className="ac-button" href="/precos">Conhecer os planos <ArrowRight size={16} /></Link></section><FAQ />
  </main></EditorialMotion>;
}

